image:
  file: .gitpod.dockerfile

tasks:
  - name: Starting server
    init: go get && go build main.go
    command: |
      gp ports await 5432
      sh createdb.sh
      go run main.go

ports:
  - port: 8000
    onOpen: open-browser
    visibility: public

  - port: 5432


